# Render.com Deployment Configuration
# UPSC Current Affairs FastAPI Backend
# Optimized for: Free tier, daily 6 PM execution, minimal costs

services:
  # FastAPI Backend Service
  - type: web
    name: upsc-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: ./

    # Service configuration
    plan: free  # Render free tier
    region: singapore  # Closest to India for better performance

    # Health check configuration
    healthCheckPath: /api/health

    # Auto-deploy on push to main branch
    branch: main

    # Environment variables (sensitive values set in Render dashboard)
    envVars:
      # Application environment
      - key: ENVIRONMENT
        value: production

      # API documentation (disabled in production)
      - key: API_DOCS_ENABLED
        value: false

      # Logging configuration
      - key: LOG_LEVEL
        value: INFO

      # Performance settings optimized for free tier
      - key: MAX_ARTICLES_PER_SOURCE
        value: 50

      - key: MIN_UPSC_RELEVANCE
        value: 40

      - key: CACHE_TTL_MINUTES
        value: 15

      # CORS origins (add your frontend domain)
      - key: CORS_ORIGINS
        value: '["http://localhost:3000","https://upsc-kappa.vercel.app"]'

      # Port configuration (Render auto-assigns)
      - key: PORT
        value: 8000

      # =================================================================
      # SENSITIVE ENVIRONMENT VARIABLES - SET IN RENDER DASHBOARD
      # =================================================================
      # Navigate to: Dashboard > Service > Environment > Add Environment Variable
      #
      # Required variables:
      # 1. FASTAPI_API_KEY - Backend authentication key
      # 2. SUPABASE_URL - Your Supabase project URL
      # 3. SUPABASE_SERVICE_ROLE_KEY - Supabase service role key
      #
      # AI API KEYS (MULTI-KEY ROTATION FOR RATE LIMIT AVOIDANCE):
      #
      # GROQ KEYS (use comma-separated for multiple keys):
      # 4. GROQ_API_KEYS - Comma-separated Groq API keys (RECOMMENDED)
      #    Example: key1,key2,key3,key4,key5,key6,key7,key8,key9,key10
      #    Recommended: 10+ keys for sufficient capacity
      #    NOTE: No spaces around commas!
      #
      # GEMINI KEYS (use comma-separated for multiple keys):
      # 5. GEMINI_API_KEYS - Comma-separated Gemini API keys (RECOMMENDED)
      #    Example: key1,key2,key3,key4,key5,key6,key7,key8,key9,key10,key11,key12,key13,key14,key15,key16,key17,key18,key19,key20
      #    Recommended: 20+ keys for 100+ requests/min capacity
      #    NOTE: No spaces around commas!
      #
      # Alternative (Legacy - NOT recommended):
      # - GEMINI_API_KEY (primary)
      # - GEMINI_API_KEY_2, GEMINI_API_KEY_3, ... (requires 20+ separate variables)
      #
      # Rate Limit Context:
      # - Groq: Varies by plan, rotation spreads load across keys
      # - Gemini Free: 5 requests/minute per key
      # - With 20 Gemini keys: 100 requests/minute total capacity
      # - Pipeline processes 25-50 articles, needs ~30-50 API calls
      # - Without rotation: Only 4-6 articles saved (rate limits)
      # - With rotation: 25-30+ articles saved successfully
      # =================================================================

      # Placeholder entries (values set via Render dashboard)
      - key: FASTAPI_API_KEY
        sync: false  # Don't sync from repo (set manually in dashboard)

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      - key: GEMINI_API_KEY
        sync: false

      - key: GROQ_API_KEY
        sync: false

    # Build configuration
    buildCommand: echo "Using Docker build from Dockerfile.render"

    # Auto-scaling configuration (free tier limits)
    autoDeploy: true

    # Render free tier specifics
    # - Service sleeps after 15 minutes of inactivity
    # - 750 hours/month free (sufficient for daily 6 PM runs)
    # - 512MB RAM, shared CPU
    # - Cold start: ~30-60 seconds

